### ISSUE TITLE
Header title customizer position selector not displaying correctly

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#13]
Header title customizer position selector is not displaying correctly

![image](https://cloud.githubusercontent.com/assets/134851/7643073/362d4bb6-fa64-11e4-9eb2-1f61c7cf3ca5.png)

**Comment by atrus1701** [comment]
this is a bug in the apl.  The stylesheet in the apl is being loaded and conflicting with vvt stylesheet for the customizer.  This update to the Organization Hub should have fixed it:
171dbd3ef6cd25876fdfb63bfc57b495e387ff2a
