### ISSUE TITLE
Enable full html and shortcode conversion in taxonomy archive descriptions

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#15]
Enable full html and shortcode conversion in taxonomy archive descriptions.  See:
http://www.paulund.co.uk/add-tinymce-editor-category-description

We may be able to do this with an existing plugin, see:
https://wordpress.org/plugins/categorytinymce/
https://wordpress.org/plugins/allow-html-in-category-descriptions/

Would be good to have execute shortcodes in taxonomy descriptions, see:
http://wordpress.stackexchange.com/questions/175752/how-to-create-a-shortcode-to-display-a-category-description

In particular, would be good to be able to add our D3 word cloud widget shortcode...

**Comment by marpa** [comment]
Here's details related to enabling full html and shortcode for taxonomy archive descriptions

**Comment by atrus1701** [comment]
df98f3da150f3132480298e83b787edb68128e50

**Comment by marpa** [comment]
Add TinyMce editor to taxonomy archive description field, see:
http://www.paulund.co.uk/add-tinymce-editor-category-description

**Comment by atrus1701** [comment]
We have opted to use a third-party plugin called Visual Term Description Editor.
