### ISSUE TITLE
Add sticky header

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#17]
Add sticker header that appears after users scroll past the top navigation.  Sticky header should include the site title (and the UNC Charlotte logo for UNCC variations) aligned left.  For how to get sticky header to work with wordpress admin bar, see:
http://www.sitepoint.com/getting-sticky-headers-wordpress-admin-bar-behave/

**Comment by atrus1701** [comment]
3a94ba273d16c3fc63567056366eb29bbf317680

**Comment by atrus1701** [comment]
0e8bc328745769e8fba3e2defb03d1a13bda4738
