### ISSUE TITLE
Fix issues resulting from multiple protocols

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#2]
Issues arise when content is loaded using one protocol (e.g. https) and calls are made to content (i.e. javascript files) using another protocol (e.g. http).

Currently the Header title customizer options are not loading in preprod because of protocol mis-matching when loading necessary javacript

**Comment by atrus1701** [comment]
6ee3bc8cb355e2728c20ef0c40206afca6e5e674
