### ISSUE TITLE
Pages widget navigation arrow images not appearing

### ISSUE THREAD

**Issue by clas-web** [clas-web/variations-template-theme#20]
list arrow images not appearing, browser error:
https://clas-incubator-wp.uncc.edu/responsive/wp-content/themes/variations-template-theme/variations/default/images/list-arrow-right.png 
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by clas-web** [comment]
Might be better to use icon fonts or utf-8 geometric shapes, see:
http://www.w3schools.com/charsets/ref_utf_geometric.asp

**Comment by atrus1701** [comment]
3a94ba273d16c3fc63567056366eb29bbf317680
