### ISSUE TITLE
Favicon not displaying

### ISSUE THREAD

**Issue by clas-web** [clas-web/variations-template-theme#22]
Favicon not displaying.  Compare:
https://clas-incubator-wp.uncc.edu/responsive/
https://clas-incubator-wp.uncc.edu/theme-tests01/

The 2nd site uses the UNC Charlotte theme (i.e. the stand-alone theme)

**Comment by atrus1701** [comment]
3a94ba273d16c3fc63567056366eb29bbf317680
templates/page/standard.php
