### ISSUE TITLE
Replace logo images with icon fonts

### ISSUE THREAD

**Issue by clas-web** [clas-web/variations-template-theme#23]
Replace logo images with icon fonts

**Comment by clas-web** [comment]
Here's link to official logo images, see:
http://advancement.uncc.edu/university-communications/services/brand-standards/university-logo

**Comment by atrus1701** [comment]
3a94ba273d16c3fc63567056366eb29bbf317680

**Comment by atrus1701** [comment]
Have created the logo icon set, and will use when I get to the UNCC variations.

**Comment by atrus1701** [comment]
0e8bc328745769e8fba3e2defb03d1a13bda4738
