### ISSUE TITLE
Hide admin bar on mobile view when not authenticated

### ISSUE THREAD

**Issue by clas-web** [clas-web/variations-template-theme#24]
Hide admin bar on mobile view when not authenticated.

**Comment by clas-web** [comment]
If we hide the admin bar,  UNC Charlotte version of the default variation should show the logo to the left of the title.  Since the logo can only be displayed on a black or white background, the UNC Charlotte version of the default variation sticky header should only be white (for light variation) or black (for dark variation).  Light variation should get the green logo, while the dark variation should get the white logo.

Logo used in the sticky header should be the version with "UNC Charlotte" directly before the crown.  Other css changes:
- set sticky header opacity to 0.9
- set text color to #333
- remove text shadows
- allow title to wrap to 2 lines

![vtt-uncc-light-mobile01](https://cloud.githubusercontent.com/assets/3451963/8533081/9ad26338-2400-11e5-99db-59133ceb689f.png)

**Comment by atrus1701** [comment]
21957fe48063972ac3d702ea1dcdcd773ab08ef7
