### ISSUE TITLE
Header text background image color picker submission action not working right

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#28]
Header text background image color picker submission action not working right.  Color does not update until the opacity is adjusted.  As well clear button doesn't reset to default

**Comment by marpa** [comment]
The color picker does work properly if you click and drag the picker "circle" icon to a new location in the picker UI

(clear button does not work...)

**Comment by atrus1701** [comment]
ed26f88df6937ec362a6bae649e61cb726e08755
