### ISSUE TITLE
Color of site description text cannot be customized with css

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#32]
Both the site title and description use inline css to define their color and background color.  This makes it hard to customize via CSS

Options:
1. Add description text color option to customizer
2. remove inline css for at least the description text

Perhaps there's some rationale for using inline css.  I can see why this is done for the site title, since its color must be changed when added to the black sticky header.

However, since the description text is not included in the sticky header, it may not need to be updated based on media query breakpoints...

**Comment by atrus1701** [comment]
You can override the description text color by using an !important tag on the css.
