### ISSUE TITLE
Search results produces error

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#33]
When the search results page is displayed, there is the following error:
Parse error: syntax error, unexpected '<' in /home/pages/public_html/wp-content/themes/variations-template-theme/templates/content/search.php on line 16

See:
https://clas-pages.uncc.edu/techne/?s=photo

**Comment by atrus1701** [comment]
df9e33b0263f87ec0a2704a0ee95ff90fe9c79bd
