### ISSUE TITLE
Use site tagline as source for default VTT site description and synch

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#34]
Use site tagline as source for default VTT site description (Dashboard > Settings > General).  Sync changes made in VTT site description to the general settings and vice-versa

Currently sites created with Org Hub add the description to the general settings but these are NOT being copied into the VTT site description...

**Comment by atrus1701** [comment]
21b516e2fc01f51f50068babd92430298447e0e6

**Comment by marpa** [comment]
Ideally the site title tagline (Dashboard > Settings > General) defines the defaults for VTT site title and description and changes made in VTT site description to the general settings and vice-versa are sychronized.

**Comment by atrus1701** [comment]
642cd7b284243eebe4fdc50d2c9c9c97e67acfb8
