### ISSUE TITLE
Reorganize theme options in the customizer

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#36]
Reorganize theme options in the customizer as follows:

Variation
Site Title and Tagline (WP 4.3 changes this to Site Identity)
Header Text
- hide option
- Position
- Header Text Color
- Header Text Background Color

Header Image
Featured Image
Background
- Background Color
- Background Image

Navigation (WP 4.3 changes this to Menu)
Widgets
Static Front Page

**Comment by atrus1701** [comment]
642cd7b284243eebe4fdc50d2c9c9c97e67acfb8
