### ISSUE TITLE
Author pages display error

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#38]
Author pages display the following error:

> Warning: Missing argument 1 for vtt_get_page_listing_name(), called in /home/pages/public_html/wp-content/themes/variations-template-theme/variations/default/templates/content/listing.php on line 14 and defined in /home/pages/public_html/wp-content/themes/variations-template-theme/functions.php on line 181

see:
https://clas-pages.uncc.edu/oat/author/achapin1/

**Comment by atrus1701** [comment]
a08c6783d9e37abb1f5bf2bf0fab1cab0abb386d
