### ISSUE TITLE
Printing Issues

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#46]
Content sometimes falls behind the header when printing pages.  This may be due to the fact that the header is fixed and so prints on every page.  Not able to allows replicate this issue.

The following media query fixes this:
```
@media print {
	#responsive-title{position:relative}
	#header-wrapper{display:none;}
}
```

**Comment by akforsyt** [comment]
This issue appears to only exist in Chrome browser.

**Comment by akforsyt** [comment]
Added print media query to CSS.  58da15a6694fbc57846f01dc50a0747830ce5735
