### ISSUE TITLE
Add inventory variation template changes to VTT default light variation

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#51]
The Inventory variation changes the following template files:

- content/listing.php
- content/search.php
- content/single.php
- part/content.php
- part/header-title.php
- post/listing.php

For each of these template files do the following:

1. identify differences in the Inventory variation template files from the VTT defaults
3. convert HTML related to the [Collections for VTT plugin](https://github.com/clas-web/collections-vtt) functionality into one or more functions with names that are prefixed with "collections_<<name>>.
3. Define these new collections_ functions in the collection-vtt plugin collections.php file
4. Add these new functions to the corresponding VTT template files using 
if (function_exists("function-name"))

**Comment by marpa** [comment]
This has been done in the collections-integration branch of this repo

**Comment by rmccal14** [comment]
https://github.com/clas-web/variations-template-theme/commit/84d9dd53d30dbfdecb4f776793dafe7732264ff2
