### ISSUE TITLE
Add Featured Page option from the New Hub variation of the UNC Charlotte child theme

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#52]
The UNC Charlotte News Hub variation of the UNC Charlotte Theme child of VTT contains a "featured story" option which does the following:

- If a post has a "featured image" and the customizer specifies this featured image to be in the Header Image position, then it will be displayed edge-to-edge and the title of the page will be floated on top of the header image
- all sidebars will be removed creating a single column layout
-paragraphs of text will be constrained to 900px wide
-images will be unconstrained so that their original size will be preserved OR the image will be displayed edge-to-edge

The template files and css used to create "featured story" pages in the News Hub variation should be copied over to the VTT default theme

**Comment by marpa** [comment]
Here are the commits from the UNC Charlotte theme repo that are most relevant:

- [add support for conditional featured stories](https://github.com/clas-web/unc-charlotte-theme/commit/f9f3d70e81cd3a9a974a5061de069678d295d206)
- [add support for different display of featured story headings](https://github.com/clas-web/unc-charlotte-theme/commit/acc8056909ed503c7363af701ddf05bb1edb6b95)
- [added ACF function for creating custom field](https://github.com/clas-web/unc-charlotte-theme/commit/cfd65e220b0752e1808a38e55c42dad1f1944d32)
- [add is_plugin_active function to prevent errors](https://github.com/clas-web/unc-charlotte-theme/commit/34d1eb3066a8c21749a5a6eb38b517c3a7984265)
- [debug featured story conditional logic](https://github.com/clas-web/unc-charlotte-theme/commit/9672673b70f5ba066f66d24ef75c06dd3c4c8aea)

**Comment by marpa** [comment]
The "featured story" option currently implemented in the News Hub variation only works with posts (i.e. post-type = post). This should also be implemented for static pages (i.e. post-type = page)

**Comment by marpa** [comment]
Featured Story options currently work ONLY IF there is a featured image.... If all the featured story settings could work W/O a featured image, then users could use any image as a header simply by making it the first block of the post/page

**Comment by rmccal14** [comment]
Hey @marpa I've tested a number of sites for Featured Story, here's 5 of them:

exchange: https://devexchange.uncc.edu/test/
gardens: https://devsites.uncc.edu/gardens/testing-featured-story/
inside clas: https://devsites.uncc.edu/inside-clas/testing-featured-story/
brooklyn oral history: https://devsites.uncc.edu/brooklyn-oral-history/testing-featured-story/
food oral history: https://devsites.uncc.edu/food-oral-history/2019/10/14/featured-story-test/

Please review and let me know what you think.

**Comment by rmccal14** [comment]
Pushed to prod, see: #53
