### ISSUE TITLE
Header menu not appearing on many VTT sites

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#54]
Header menu not appearing on all VTT sites except those using the Epsilon variations.

https://github.com/clas-web/variations-template-theme/blob/5060e9b5a76ecf5a52e9d779bb015643f0e6fbbf/variations/light/templates/part/main.php#L67

The conditional should be changed to:
`if ( has_nav_menu( 'header-navigation' ) ) {`\

Not sure of the full impact of this change...

**Comment by marpa** [comment]
Here's where this code was added, see:
[Add header navigation menu if not already loaded and Featured Story changes](https://github.com/clas-web/variations-template-theme/commit/ae34b3ceb82c75b0e9d55f3599384e0f1f1ee34c#r36018892)

**Comment by marpa** [comment]
The above update breaks header menus for other variations (uncc-epsilon, uncc-news-hub). The additional conditions need to be included:
`! function_exists('epsilon_enqueue_scripts')`
`! function_exists( 'nhs_get_wpquery_section')`

Updated line should thus be:
`if (  has_nav_menu( 'header-navigation' ) && ! function_exists( 'nhs_get_wpquery_section') && ! function_exists('epsilon_enqueue_scripts')) {`

**Comment by rmccal14** [comment]
Resolved in https://github.com/clas-web/variations-template-theme/commit/5857c96283c3d07a43a86434cbc5c4515a756431
